description = "Executes the BMad Task: Game Design Brainstorming"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{.bmad-2d-phaser-game-dev/tasks/game-design-brainstorming.md}
"""